# Generated by Django 4.2.7 on 2024-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_templates_delete_codingproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='link_template',
            field=models.CharField(default='', max_length=255),
        ),
    ]
