# Generated by Django 4.2.7 on 2024-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_templates_link_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='id_user',
            field=models.CharField(max_length=255),
        ),
    ]
