# Generated by Django 4.2.7 on 2024-08-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_templates_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='description',
            field=models.CharField(default='No description', max_length=100),
            preserve_default=False,
        ),
    ]
